spring:
  application:
    name: activity-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/fitnessactivity
      database: fitnessactivity
server:
  port: 8082
#mongodb://localhost:27017/
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/