#spring.application.name=aiservice
spring:
    application:
        name: ai-service
    data:
        mongodb:
            uri: mongodb://localhost:27017/fitnessrecommendation
            database: recommendation
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
server:
    port: 8083




